import React, { useEffect } from "react";
import { assets } from "../assets/assets";
import moment from "moment";
import Markdown from "react-markdown";
import Prism from "prismjs";

const Message = ({ message, index }) => {
  useEffect(() => {
    Prism.highlightAll();
  }, [message.content]);

  return (
    <div className="animate-fade-in">
      {message.role === "user" ? (
        <div className="flex items-start justify-end my-4 gap-3">
          <div className="group flex flex-col gap-2 p-4 bg-gradient-to-br from-blue-500 to-purple-600 text-white rounded-2xl max-w-2xl shadow-lg hover:shadow-xl transition-all duration-300">
            <p className="text-sm">{message.content}</p>
            <span className="text-xs text-blue-100 opacity-80">
              {moment(message.timestamp).fromNow()}
            </span>
          </div>
          <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-500 rounded-full flex items-center justify-center shadow-md">
            <img src={assets.user_icon} alt="User" className="w-5 rounded-full" />
          </div>
        </div>
      ) : (
        <div className="flex items-start gap-3 my-4">
          <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center shadow-md">
            <span className="text-white font-bold text-sm">O</span>
          </div>
          <div className="group flex flex-col gap-2 p-4 max-w-2xl bg-white/80 dark:bg-[#57317C]/30 border border-gray-200 dark:border-[#80609F]/30 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300">
            {message.isImage ? (
              <div className="relative group/image">
                <img
                  src={message.content}
                  alt="Generated by Oryn"
                  className="w-full max-w-md mt-2 rounded-xl shadow-md group-hover/image:scale-105 transition-transform duration-300"
                />
                <div className="absolute top-2 right-2 opacity-0 group-hover/image:opacity-100 transition-opacity duration-300">
                  <div className="bg-black/50 text-white text-xs px-2 py-1 rounded-lg">
                    Generated by Oryn
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-sm text-gray-800 dark:text-white reset-tw">
                <Markdown>{message.content}</Markdown>
              </div>
            )}
            <div className="flex items-center justify-between">
              <span className="text-xs text-gray-500 dark:text-[#B1A6C0]">
                {moment(message.timestamp).fromNow()}
              </span>
              <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <button className="p-1 hover:bg-gray-200 dark:hover:bg-gray-600 rounded transition-colors duration-200">
                  <span className="text-xs">👍</span>
                </button>
                <button className="p-1 hover:bg-gray-200 dark:hover:bg-gray-600 rounded transition-colors duration-200">
                  <span className="text-xs">👎</span>
                </button>
                <button className="p-1 hover:bg-gray-200 dark:hover:bg-gray-600 rounded transition-colors duration-200">
                  <span className="text-xs">📋</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Message;
